-- Format for overwriting define values:
--
-- NDefines.NDiplomacy.MAX_CLIENT_STATES = 99

NDefines.NEngine.EVENT_PROCESS_OFFSET = 40

NDefines.NGame.END_DATE = "2044.12.31"
NDefines.NCountry.FREE_IDEA_GROUP_COST = 6

NDefines.NCountry.DISMANTLE_HRE_PRESTIGE = 200

NDefines.NCountry.PS_ARTILLERY_BARRAGE = 25
NDefines.NCountry.PS_NAVAL_BARRAGE = 25
NDefines.NCountry.PS_ASSAULT = 50

NDefines.NCountry.LIBERTY_DESIRE_RELATIVE_POWER = 115
NDefines.NCountry.DIVERT_TRADE_LIBERTY = 50
NDefines.NCountry.EMBARGO_RIVALS_LIBERTY = 10
NDefines.NCountry.MAX_CROWN_COLONIES = 7

NDefines.NCountry.INNOVATIVENESS_MAX = 10000
NDefines.NCountry.INNOVATIVENESS_FIRST_REACHED_TECH_LEVEL = 2
NDefines.NCountry.INNOVATIVENESS_FIRST_PICKED_IDEA = 1

NDefines.NCountry.IDEA_TO_TECH = 0.01
NDefines.NCountry.TECH_TIME_COST = 0.32
NDefines.NCountry.TECH_AHEAD_OF_TIME = 0.0
NDefines.NCountry.YEARS_UNTIL_BROKEN = 1
NDefines.NCountry.MIN_DEVELOPMENT_FOR_GOV_RANK_2 = 150		-- Need at least this much development to upgrade to government rank 2
NDefines.NCountry.MIN_DEVELOPMENT_FOR_GOV_RANK_3 = 1000
NDefines.NCountry.PS_STRENGTHEN_GOVERNMENT = 75
NDefines.NCountry.ABDICATE_LEGITIMACY_THRESHOLD = 0
NDefines.NCountry.ABDICATE_AGE_THRESHOLD = 15
NDefines.NCountry.ABDICATE_RULING_LENGTH_THRESHOLD = 0

NDefines.NCountry.REVOLUTION_SPREAD_COUNT = 3
NDefines.NCountry.REVOLUTION_DAILY_SPREAD = 1.2
NDefines.NCountry.REVOLUTION_CLAIM_MIN_ZEAL = 1.0
NDefines.NCountry.MAXIMUM_ADVISOR_SKILL = 10

NDefines.NCountry.PS_FACTION_BOOST = 500

NDefines.NCountry.STARTING_ARMY_SIZE_REBEL_THREAT = 0.01

NDefines.NCountry.REVOLT_SIZE_BASE = 1
NDefines.NCountry.REVOLT_TECH_IMPACT = 0.06
NDefines.NCountry.REVOLT_TECH_MORALE = 0.06

NDefines.NCountry.REBEL_ARTILLERY_INCREASE_LEVEL_2_TECH = 25
NDefines.NCountry.REBEL_ARTILLERY_INCREASE_LEVEL_2_SIZE = 0.5

NDefines.NCountry.OVERSEAS_CLIENT_STATES = 1

NDefines.NCountry.EXPLOIT_COOLDOWN_MONTHS = 120

NDefines.NCountry.PS_SCORCH_EARTH = 50

NDefines.NCountry.PROVOKE_REVOLT_MIN_PROGRESS = 10.0

NDefines.NCountry.PS_REDUCE_WAREXHAUSTION = 75.0

NDefines.NCountry.PS_IMPROVE_PROVINCE_BASE = 150
NDefines.NCountry.PS_IMPROVE_PROVINCE_CAPITAL_DISCOUNT = 0.5
NDefines.NCountry.PS_BUY_IDEA = 200

NDefines.NCountry.PS_CHANGE_CULTURE = 25
NDefines.NCountry.PS_CHANGE_CULTURE_OVERSEAS_RELIGION_MOD = 0.0



NDefines.NMilitary.MIN_MONTHLY_MANPOWER = 0.0

NDefines.NMilitary.REBEL_RELOCATION_DISTANCE_MAX = 200000

NDefines.NMilitary.REBEL_LEADER_POWER = 30

NDefines.NAI.DEVELOPMENT_CAP_BASE = 500
NDefines.NAI.DEVELOPMENT_CAP_MULT = 50

NDefines.NAI.DEBASE_THRESHOLD = 0

NDefines.NAI.CORRUPTION_BUDGET_FRACTION = 5.0
NDefines.NAI.AGGRESSIVENESS = 200
NDefines.NAI.AGGRESSIVENESS_BONUS_EASY_WAR = 9000


NDefines.NAI.REPAY_LOAN_BASE_AI_DESIRE = 100
NDefines.NAIEconomy.LOAN_REPAYMENT_SAVINGS_PRIORITY = 100
NDefines.NAIEconomy.LOAN_REPAYMENT_SAVINGS_PRIORITY_WARTIME = 1

NDefines.NDiplomacy.NUM_OF_GREAT_POWERS = 12




NDefines.NGraphics.MAX_MAPMODE_COLOR_UPDATE_DELAY_MS = 200
NDefines.NGraphics.LIGHT_DIRECTION_X = -1.0
NDefines.NGraphics.LIGHT_DIRECTION_Y = -1.0
NDefines.NGraphics.LIGHT_DIRECTION_Z = -0.5

NDefines.NGraphics.LIGHT_SHADOW_DIRECTION_X = -65
NDefines.NGraphics.LIGHT_SHADOW_DIRECTION_Y = -145
NDefines.NGraphics.LIGHT_SHADOW_DIRECTION_Z = -75

NDefines.NGraphics.BORDER_WIDTH = 4.0

NDefines.NGraphics.CITY_SPRAWL_AMOUNT = 1.5


NDefines.NNationDesigner.RULER_MIN_AGE = 15
NDefines.NNationDesigner.RULER_MAX_AGE = 80
NDefines.NNationDesigner.HEIR_MAX_AGE = 80